- name: Deploy Docker Compose App
  hosts: all
  become: yes

  tasks:
    - name: Install Docker & Docker-Compose
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - docker-compose

    - name: Copy Docker Compose file
      copy:
        src: ../docker/docker-compose.yml
        dest: /opt/docker-compose.yml

    - name: Start Application
      command: docker-compose -f /opt/docker-compose.yml up -d
