version: '3'
services:
  web:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8083:80"
    volumes:
      - ./webserver:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counterdb
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
