version: '3.8'

services:
  web:
    build: ./app
    container_name: webserver
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counterdb
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
