version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: webserver
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counterdb
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  counter:
    image: busybox:latest
    entrypoint: "sh -c 'while true; do wget -qO- --post-data=\"\" http://webserver:8080/hit; sleep 5; done'"
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge
